In [34]:
import numpy as np
from scipy.optimize import curve_fit
import matplotlib.pyplot as plt

In [24]:
x = np.arange(0, 3.5, 0.5)

In [25]:
y = x * 2 # N / cm

In [35]:
 np.random.rand()/50

0.013379975262099492

In [44]:
y

array([0., 1., 2., 3., 4., 5., 6.])

In [55]:
y_measured = abs(y + 0.025*np.random.randn(len(y))) # don't do this
y_error = np.array([(0.005) + np.random.rand()/500 for i in range(len(y_measured))])

In [56]:
y_measured

array([1.31190020e-03, 1.01190959e+00, 1.99200854e+00, 3.02098252e+00,
       3.97642765e+00, 4.99427896e+00, 5.99081569e+00])

In [41]:
y_error

array([0.0418697 , 0.0257431 , 0.04335565, 0.02978778, 0.04454821,
       0.04182307, 0.02623164])

In [60]:
hook = lambda x, k: k*x

$y(t) = a*x + b$

In [61]:
popt, pcov = curve_fit(hook, x, y, sigma=y_error, p0=[1.5]) # function, x_value, y_value, error_y_value

In [62]:
popt

array([2.])

In [63]:
pcov

array([[0.]])

In [65]:
help(curve_fit)

Help on function curve_fit in module scipy.optimize.minpack:

curve_fit(f, xdata, ydata, p0=None, sigma=None, absolute_sigma=False, check_finite=True, bounds=(-inf, inf), method=None, jac=None, **kwargs)
    Use non-linear least squares to fit a function, f, to data.
    
    Assumes ``ydata = f(xdata, *params) + eps``.
    
    Parameters
    ----------
    f : callable
        The model function, f(x, ...). It must take the independent
        variable as the first argument and the parameters to fit as
        separate remaining arguments.
    xdata : array_like or object
        The independent variable where the data is measured.
        Should usually be an M-length sequence or an (k,M)-shaped array for
        functions with k predictors, but can actually be any object.
    ydata : array_like
        The dependent data, a length M array - nominally ``f(xdata, ...)``.
    p0 : array_like, optional
        Initial guess for the parameters (length N). If None, then the
        initi

In [64]:
f = lambda x, s1, s2, v1, v2: s1*s2*x + v1 + v2